baseURL = "https://filip.world/"
languageCode = "en-us"
title = "filip.world"
theme = "notrack"
newContentEditor = "vim"
# mainSections = ["blog"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "Filip"
  siteHeading = "filip.world" # defaults to author
  favicon = "" # Adds a small icon next to the page title in a tab
  showBlogLatest = false
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post om the home page
  blogLatestHeading = "My writing"

  [params.social]
    email = "f@filip.world"
    telegram = "filipvv"
    github = "filipvvv"
    rss = ""

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
